{{- if .Values.components.contentService.remoteStorage.gcloud.credentialsFileUpload }}
apiVersion: v1
kind: Secret
metadata:
  name: ws-sync-gcloud
  labels:
    app: {{ template "gitpod.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  "{{ base .Values.components.contentService.remoteStorage.gcloud.credentialsFile }}": {{ $.Files.Get (print (base .Values.components.contentService.remoteStorage.gcloud.credentialsFile)) | b64enc | quote }}
{{- end }}
